const express = require("express");
const controller = require("../controllers/catalogRequest.controller");
const { authRequired, requireRole } = require("../middleware/auth");
const { requireApprovedVendor } = require("../middleware/vendorApproval");
const router = express.Router();
router.get("/search", authRequired, requireRole("vendor"), requireApprovedVendor, controller.searchCatalog);
router.get("/requests", authRequired, requireRole("vendor"), requireApprovedVendor, controller.listVendorRequests);
router.post("/request", authRequired, requireRole("vendor"), requireApprovedVendor, controller.createRequest);
router.get("/request/:id", authRequired, requireRole("vendor"), requireApprovedVendor, controller.getRequestById);
router.put("/request/:id/cancel", authRequired, requireRole("vendor"), requireApprovedVendor, controller.cancelRequest);
router.get("/admin/requests", authRequired, requireRole("admin", "super_admin", "support_admin", "finance_admin"), controller.listAdminRequests);
router.get("/admin/request/:id", authRequired, requireRole("admin", "super_admin", "support_admin", "finance_admin"), controller.getRequestById);
router.put("/admin/request/:id/approve", authRequired, requireRole("admin", "super_admin", "support_admin", "finance_admin"), controller.reviewRequest);
router.put("/admin/request/:id/reject", authRequired, requireRole("admin", "super_admin", "support_admin", "finance_admin"), controller.reviewRequest);
router.put("/admin/request/:id/request-info", authRequired, requireRole("admin", "super_admin", "support_admin", "finance_admin"), controller.reviewRequest);
router.put("/admin/request/:id/merge", authRequired, requireRole("admin", "super_admin", "support_admin", "finance_admin"), controller.reviewRequest);
module.exports = router;