import {
  ShieldAlert,
  BarChart3,
  Brush,
  Boxes,
  CreditCard,
  FileSearch,
  FolderTree,
  HeadphonesIcon,
  Image,
  Lightbulb,
  LayoutDashboard,
  Package,
  Package2,
  Percent,
  RotateCcw,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Star,
  Tags,
  Truck,
  Users,
  Wallet,
  UserCog,
  Clapperboard,
  Megaphone,
  Search,
  Link as LinkIcon,
  FileCheck2,
  LineChart,
  PackageCheck,
  SlidersHorizontal,
  Undo2,
} from "lucide-react";

export const ADMIN_PRIMARY_ITEM = {
  name: "Dashboard",
  path: "/admin/dashboard",
  icon: LayoutDashboard,
};

export const ADMIN_SECTION_ITEMS = [
  {
    section: "Influencer Commerce",
    key: "influencer-commerce",
    notificationModule: "GROWTH",
    items: [
      {
        name: "Overview",
        key: "influencer-commerce-overview",
        icon: BarChart3,
        children: [
          { name: "Dashboard", path: "/admin/influencer-commerce", permission: "influencerCommerce.dashboardRead", icon: BarChart3, exact: true, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
        ],
      },
      {
        name: "People",
        key: "influencer-commerce-people",
        icon: Users,
        children: [
          { name: "Influencers", path: "/admin/influencer-commerce/influencers", permission: "influencerCommerce.influencersRead", icon: Users, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
          { name: "Vendors", path: "/admin/influencer-commerce/vendors", permission: "influencerCommerce.vendorsRead", icon: ShoppingBag, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
          { name: "Influencer-Vendor Matching", path: "/admin/influencer-commerce/matching", permission: "influencerCommerce.influencerVendorMatchingRead", icon: Lightbulb, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
        ],
      },
      {
        name: "Campaigns",
        key: "influencer-commerce-campaigns",
        icon: Megaphone,
        children: [
          { name: "Campaign Management", path: "/admin/influencer-commerce/campaigns", permission: "influencerCommerce.campaignsRead", icon: Megaphone, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
          { name: "Vendor Campaign Commission", path: "/admin/influencer-commerce/vendor-campaign-commission", permission: "influencerCommerce.vendorCampaignCommissionRead", icon: Percent, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
        ],
      },
      {
        name: "Affiliate & Products",
        key: "influencer-commerce-affiliate",
        icon: LinkIcon,
        children: [
          { name: "Affiliate Links", path: "/admin/influencer-commerce/affiliate-links", permission: "influencerCommerce.affiliateLinksRead", icon: LinkIcon, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
          { name: "Affiliate Tracking", path: "/admin/influencer-commerce/tracking", permission: "influencerCommerce.affiliateTrackingRead", icon: Search, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
          { name: "Product Promotions", path: "/admin/influencer-commerce/promotions", permission: "influencerCommerce.productPromotionsRead", icon: Package, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
        ],
      },
      {
        name: "Finance",
        key: "influencer-commerce-finance",
        icon: Wallet,
        children: [
          { name: "Escrow & Settlements", path: "/admin/influencer-commerce/settlements", permission: "influencerCommerce.settlementsRead", icon: Wallet, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
          { name: "Campaign Finance", path: "/admin/influencer-commerce/campaign-finance", permission: "influencerCommerce.campaignFinanceRead", icon: Wallet, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
          { name: "Revenue Dashboard", path: "/admin/influencer-commerce/revenue", permission: "influencerCommerce.revenueDashboardRead", icon: Percent, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
          { name: "Payout Management", path: "/admin/influencer-commerce/payouts", permission: "influencerCommerce.payoutsRead", icon: Wallet, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
        ],
      },
      {
        name: "Configuration",
        key: "influencer-commerce-configuration",
        icon: Settings,
        children: [
          { name: "Tier & Score Config", path: "/admin/influencer-commerce/configuration", permission: "influencerCommerce.tierScoreConfigRead", icon: SlidersHorizontal, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
          { name: "Settings", path: "/admin/influencer-commerce/settings", permission: "influencerCommerce.settingsRead", icon: Settings, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
        ],
      },
    ],
  },
  {
    section: "Overview",
    key: "overview",
    items: [
      { name: "Analytics", path: "/admin/analytics", permission: "analytics.read", icon: BarChart3 },
      { name: "Revenue", path: "/admin/revenue", permission: "revenue.read", icon: Wallet },
      { name: "Audit Logs", path: "/admin/audit-logs", permission: "auditLogs.read", icon: FileSearch },
    ],
  },
  {
    section: "Management",
    notificationModule: "MANAGEMENT",
    key: "management",
    items: [
      { name: "Users", path: "/admin/users", permission: "users.read", icon: Users, notificationModule: "MANAGEMENT", notificationSubModule: "USERS" },
      { name: "Sellers", path: "/admin/sellers", permission: "sellers.read", icon: ShoppingBag },
      { name: "Products", path: "/admin/products", permission: "products.read", icon: Boxes, notificationModule: "MANAGEMENT", notificationSubModule: "PRODUCTS" },
      { name: "Inventory", path: "/admin/inventory", permission: "inventory.read", icon: Package2, notificationModule: "MANAGEMENT", notificationSubModule: "INVENTORY" },
      { name: "Orders", path: "/admin/orders", permission: "orders.read", icon: ShoppingCart, notificationModule: "MANAGEMENT", notificationSubModule: "ORDERS" },
      { name: "Pickups", path: "/admin/pickups", permission: "pickups.read", icon: Truck, notificationModule: "MANAGEMENT", notificationSubModule: "DELIVERY" },
      { name: "Reviews", path: "/admin/reviews", permission: "reviews.read", icon: Star, notificationModule: "MANAGEMENT", notificationSubModule: "REVIEWS" },
    ],
  },
  {
    section: "Catalog",
    key: "catalog",
    items: [
      { name: "Categories", path: "/admin/categories", permission: "categories.read", icon: FolderTree },
      { name: "Subcategories", path: "/admin/subcategories", permission: "subcategories.read", icon: Tags },
      { name: "Return Rules", path: "/admin/return-rules", permission: "returnRules.read", icon: RotateCcw },
      { name: "Catalog Requests", path: "/admin/catalog-requests", permission: "catalogRequests.read", icon: FileSearch },
      { name: "Attributes", path: "/admin/attributes", permission: "attributes.read", icon: Tags },
      { name: "Product Modules", path: "/admin/product-modules", permission: "productModules.read", icon: Boxes },
      { name: "Homepage Containers", path: "/admin/homepage-containers", permission: "homepageContainers.read", icon: Image },
      { name: "Homepage Builder", path: "/admin/marketing/homepage-builder", permission: "homepageBuilder.read", icon: LayoutDashboard },
      { name: "Vendor Access", path: "/admin/vendor-access", permission: "vendorAccess.read", icon: ShieldCheck },
      { name: "Shipping Access", path: "/admin/vendor-access/shipping", permission: "shippingAccess.read", icon: Truck },
    ],
  },
  {
    section: "Commerce Intelligence",
    key: "commerce-intelligence",
    items: [
      { name: "Recommendation Settings", path: "/admin/commerce-intelligence/settings", permission: "recommendationSettings.read", icon: Lightbulb },
      { name: "Related Products Engine", path: "/admin/commerce-intelligence/related-products", permission: "relatedProducts.read", icon: Lightbulb },
      { name: "Frequently Bought Together", path: "/admin/commerce-intelligence/frequently-bought-together", permission: "frequentlyBoughtTogether.read", icon: Lightbulb },
      { name: "Cross Sell Rules", path: "/admin/commerce-intelligence/cross-sell", permission: "crossSellRules.read", icon: Lightbulb },
      { name: "Upsell Rules", path: "/admin/commerce-intelligence/upsell", permission: "upsellRules.read", icon: Lightbulb },
      { name: "Recommendation Analytics", path: "/admin/commerce-intelligence/analytics", permission: "recommendationAnalytics.read", icon: BarChart3 },
      { name: "AI Scoring Rules", path: "/admin/commerce-intelligence/ai-scoring", permission: "aiScoringRules.read", icon: Lightbulb },
      { name: "Recommendation Preview", path: "/admin/commerce-intelligence/preview", permission: "recommendationPreview.read", icon: FileSearch },
      { name: "Cache Management", path: "/admin/commerce-intelligence/cache", permission: "cacheManagement.read", icon: RotateCcw },
    ],
  },
  {
    section: "Finance",
    notificationModule: "FINANCE",
    key: "finance",
    items: [
      { name: "Payments", path: "/admin/payments", permission: "payments.read", icon: CreditCard, notificationModule: "FINANCE", notificationSubModule: "PAYMENTS" },
      { name: "Refunds", path: "/admin/refunds", permission: "refunds.read", icon: RotateCcw, notificationModule: "MANAGEMENT", notificationSubModule: "RETURNS" },
      { name: "Returns", path: "/admin/returns", permission: "returns.read", icon: RotateCcw, notificationModule: "MANAGEMENT", notificationSubModule: "RETURNS" },
      { name: "Escrow Refunds", path: "/admin/finance/escrow-refunds", permission: "escrowRefunds.read", icon: RotateCcw, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
      { name: "Cancellation Policies", path: "/admin/finance/cancellation-policies", permission: "cancellationPolicies.read", icon: ShieldCheck, notificationModule: "FINANCE", notificationSubModule: "SETTINGS" },
      { name: "COD Advance", path: "/admin/finance/cod-advance", permission: "codAdvance.read", icon: SlidersHorizontal, notificationModule: "FINANCE", notificationSubModule: "SETTINGS" },
      { name: "Invoices", path: "/admin/finance/invoices", permission: "invoices.read", icon: FileSearch, notificationModule: "FINANCE", notificationSubModule: "PAYMENTS" },
      { name: "Payout Management", path: "/admin/finance/payouts", permission: "payouts.read", icon: Wallet, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
      { name: "Commission", path: "/admin/commission", permission: "commission.read", icon: Percent, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
      { name: "Influencers", path: "/admin/influencers", permission: "financeInfluencers.read", icon: Clapperboard },
    ],
  },
  {
    section: "Workspace",
    notificationModule: "WORKSPACE",
    key: "workspace",
    items: [
      { name: "Settings", path: "/admin/settings", permission: "settings.read", icon: Settings, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
      { name: "Company Branding", path: "/admin/settings/company-branding", permission: "branding.read", icon: Brush, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
      { name: "Platform Maintenance", path: "/admin/settings/maintenance", permission: "maintenance.read", icon: ShieldAlert, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
      { name: "Shipping", path: "/admin/shipping", permission: "shipping.read", icon: Truck },
      { name: "Pricing", path: "/admin/pricing", permission: "pricing.read", icon: Percent },
      { name: "Pricing Categories", path: "/admin/pricing-categories", permission: "pricingCategories.read", icon: Tags },
      { name: "Staff Roles", path: "/admin/roles", permission: "roles.read", icon: ShieldCheck },
      { name: "Staff Accounts", path: "/admin/staff", permission: "staff.read", icon: UserCog },
    ],
  },
];

export const VENDOR_PRIMARY_ITEM = {
  name: "Dashboard",
  path: "/vendor/dashboard",
  icon: LayoutDashboard,
};

export const VENDOR_DYNAMIC_MODULE_META = {
  analytics: { section: "Finance", path: "/vendor/analytics", icon: BarChart3 },
  delivery: { section: "Management", path: "/vendor/delivery", icon: Truck, notificationModule: "MANAGEMENT", notificationSubModule: "DELIVERY" },
  inventory: { section: "Management", path: "/vendor/inventory", icon: Package2, notificationModule: "MANAGEMENT", notificationSubModule: "INVENTORY" },
  orders: { section: "Management", path: "/vendor/orders", icon: ShoppingCart, notificationModule: "MANAGEMENT", notificationSubModule: "ORDERS" },
  payments: { section: "Finance", path: "/vendor/finance", icon: CreditCard, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
  products: { section: "Management", path: "/vendor/products", icon: Package, notificationModule: "MANAGEMENT", notificationSubModule: "PRODUCTS" },
  returns: { section: "Management", path: "/vendor/returns", icon: RotateCcw, notificationModule: "MANAGEMENT", notificationSubModule: "RETURNS" },
  reviews: { section: "Growth", path: "/vendor/reviews", icon: Star, notificationModule: "GROWTH", notificationSubModule: "REVIEWS" },
};

export const VENDOR_STATIC_ITEMS = [
  {
    section: "Influencer Commerce",
    notificationModule: "GROWTH",
    key: "influencer-commerce",
    items: [
      { name: "Dashboard", path: "/vendor/influencer-commerce", icon: BarChart3, exact: true, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Discover Influencers", path: "/vendor/influencer-commerce/discover", icon: Search, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "My Influencers", path: "/vendor/influencer-commerce/relationships", icon: Users, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Campaign Management", path: "/vendor/influencer-commerce/campaigns", icon: Megaphone, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Delivered Products", path: "/vendor/influencer-commerce/delivered-products", icon: PackageCheck, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Returned Products", path: "/vendor/influencer-commerce/returned-products", icon: Undo2, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Media Library", path: "/vendor/influencer-commerce/media-library", icon: Image, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Content Approvals", path: "/vendor/influencer-commerce/content", icon: FileCheck2, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Influencer Performance", path: "/vendor/influencer-commerce/performance", icon: LineChart, notificationModule: "GROWTH", notificationSubModule: "INFLUENCER_COMMERCE" },
      { name: "Escrow Refunds", path: "/vendor/influencer-commerce/escrow-refunds", icon: RotateCcw, notificationModule: "FINANCE", notificationSubModule: "PAYOUTS" },
    ],
  },
  {
    section: "Workspace",
    notificationModule: "WORKSPACE",
    key: "workspace",
    items: [
      { name: "Catalog Requests", path: "/vendor/catalog-requests", icon: FileSearch },
      { name: "Ready for Pickup", path: "/vendor/pickups", icon: Truck },
      { name: "Offers", path: "/vendor/offers", icon: Percent },
      { name: "Support", path: "/vendor/support", icon: HeadphonesIcon, notificationModule: "WORKSPACE", notificationSubModule: "SUPPORT" },
      { name: "Settings", path: "/vendor/settings", icon: Settings, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
    ],
  },
];
