const INFLUENCER_CATEGORIES = [
  "baby",
  "beauty",
  "electronics",
  "fashion",
  "fitness",
  "food",
  "home",
  "lifestyle",
  "pets",
  "sports",
  "toys",
];
const INFLUENCER_STATES = ["draft", "submitted", "verified", "active", "suspended"];
const CAMPAIGN_WORKFLOW_STATUSES = [
  "draft",
  "proposed",
  "invitation_sent",
  "invitation_pending",
  "invitation_expired",
  "pending_review",
  "accepted",
  "rejected",
  "content_creation",
  "active",
  "live",
  "paused",
  "product_shipped",
  "content_in_progress",
  "content_submitted",
  "under_review",
  "revision_requested",
  "approved",
  "ready_for_publish",
  "publish_scheduled",
  "published",
  "tracking_active",
  "partially_completed",
  "content_deadline_missed",
  "completed",
  "budget_exhausted",
  "commission_cap_reached",
  "awaiting_upload",
  "upload_expired",
  "refund_eligible",
  "refund_requested",
  "refund_approved",
  "refunded",
  "refund_failed",
  "cancelled",
  "expired",
  "stopped",
];
const CAMPAIGN_STATES = CAMPAIGN_WORKFLOW_STATUSES;
const CAMPAIGN_INVITATION_STATUSES = ["invitation_sent", "viewed", "accepted", "rejected", "expired", "cancelled"];
const CAMPAIGN_ACCEPTANCE_STATUSES = ["accepted", "active", "completed", "cancelled"];
const FIXED_PAYMENT_WORKFLOW_STATUSES = [
  "awaiting_acceptance",
  "accepted_awaiting_funding",
  "funding_pending",
  "funded",
  "content_in_progress",
  "vendor_approved",
  "partially_released",
  "fully_released",
  "refund_pending",
  "refund_requested",
  "refund_approved",
  "refund_processing",
  "refund_failed",
  "refunded",
  "completed",
  "cancelled",
];
const REEL_STATES = ["uploaded", "pending_review", "approved", "published", "rejected"];
const COMMISSION_STATES = ["HOLD", "SETTLED", "CANCELLED", "REVERSED"];
const INFLUENCER_EVENTS = {
  INFLUENCER_ACTIVATED: "INFLUENCER_ACTIVATED",
  CAMPAIGN_ACTIVATED: "CAMPAIGN_ACTIVATED",
  REEL_PUBLISHED: "REEL_PUBLISHED",
  TRACKING_CREATED: "TRACKING_CREATED",
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  ORDER_ELIGIBLE_FOR_SETTLEMENT: "ORDER_ELIGIBLE_FOR_SETTLEMENT",
  COMMISSION_DISTRIBUTED: "COMMISSION_DISTRIBUTED",
};
module.exports = {
  INFLUENCER_CATEGORIES,
  INFLUENCER_STATES,
  CAMPAIGN_WORKFLOW_STATUSES,
  CAMPAIGN_INVITATION_STATUSES,
  CAMPAIGN_ACCEPTANCE_STATUSES,
  FIXED_PAYMENT_WORKFLOW_STATUSES,
  CAMPAIGN_STATES,
  REEL_STATES,
  COMMISSION_STATES,
  INFLUENCER_EVENTS,
};